# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 364f8d107fd8873abeda8d741b2d0672ac156d9df806d98e60da42b81c240eddcf1193dafbc15d4612e5dcbb859c44791924a10efe43f26b095c6b7d45d53d80

test:
  secret_key_base: 38fc7e774e565cd54e1238e35d879c199494efe344ff5fea14469ae1b9274fa891afe1923c9f1afad03ad101ae4b6edb54c0132d2957423de1bf31084ca379a8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
